Remove failed test simulation from build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,5 +30,5 @@ jobs:
       - name: Build with Turbo
         run: pnpm turbo run build
 
-      - name: Simulate failed test
-        run: exit 1
+    #   - name: Simulate failed test
+    #     run: exit 1
